name: "Publish GitHub Release with debug .apk"

on: create

jobs:
  publish:
    name: Release .apk
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache .gradle
      uses: burrunan/gradle-cache-action@v1

    - name: Mark .gradlew as executable
      run: chmod +x ./gradlew

    - name: Build debug .apk
      run: ./gradlew assembleDebug

    - name: Upload .apk
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Get tag version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

    - name: Create artifact with debug .apk
      uses: underwindfall/create-release-with-debugapk@v2.0.0
      env: 
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: "UNN Journal Checker.apk"
        asset_content_type: application/zip
        draft: false
        prerelease: false
