name: "Publish release .apk with Gradle"

on:
  release:
    types: [published]

jobs:
  publish:
    name: Release .apk
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Mark .gradlew as executable
      run: chmod +x ./gradlew

    - name: Build debug .apk
      run: ./gradlew assembleDebug

    - name: Upload .apk
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Get tag version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Create Release and Upload debug .apk
      uses: underwindfall/create-release-with-debugapk@v2.0.0
      env: 
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: "UNN Journal Checker.apk"
        asset_content_type: application/zip
        draft: false
        prerelease: false
