name: "Publish release .apk with Gradle"

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Mark .gradlew as executable
      run: chmod +x ./gradlew

    - name: Build release .apk
      run: ./gradlew assembleRelease

    - name: Release using Hub
      uses: kyze8439690/action-release-releaseapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
       APP_FOLDER: app
